---
- hosts: all
  become: true
  tasks:
    - name: Install Apache php support
      yum:
        name:
          - httpd
          - php-fpm
        state: latest
        update_cache: yes
      when: ansible_distribution == "RedHat"

    - name: Install Apache and php support (Ubuntu)
      apt:
        name:
          - apache2
          - php
          - php-fpm
          - libapache2-mod-php
        state: latest
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
